# Generated by Django 5.1.3 on 2024-12-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the agent', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this agent does')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google')], help_text='The LLM provider to use', max_length=50)),
                ('system_prompt', models.TextField(help_text="The system prompt that defines the agent's behavior")),
                ('user_prompt_template', models.TextField(help_text='Template for the user prompt. Use {content} for document content placeholder')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this agent is active and can be used by streams')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['-created_at'],
            },
        ),
    ]
