# Generated by Django 5.1.3 on 2024-12-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agent_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='user_prompt_template',
            field=models.TextField(help_text='Template for the user prompt. Use {news} for news content placeholder'),
        ),
    ]
