version: 0.2
# https://docs.aws.amazon.com/codepipeline/latest/userguide/ecs-cd-pipeline.html

# input variables that have to be provided by the triggering pipeline:
# IMAGE_REPO_NAME
# CONTAINER_NAME

phases:
  # install:
  #   runtime-versions:
  #     docker: 20
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - AWS_REGION=$AWS_DEFAULT_REGION
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - BRANCH_NAME=${BranchName}
      - echo Pull started on `date`
      # - docker pull $REPOSITORY_URI:latest || true
      - codebuild-breakpoint

  build:
    commands:
      - echo Build started on `date`
      - ls ../
      - ls ../../
      - echo Building the Docker image...
      # - docker build -f ./Dockerfile.ecs --cache-from $REPOSITORY_URI:latest -t $REPOSITORY_URI:latest .
      - docker build -f ./Dockerfile.ecs --no-cache -t $REPOSITORY_URI:latest .
      
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"newsloom","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
