version: 0.2
# https://docs.aws.amazon.com/codepipeline/latest/userguide/ecs-cd-pipeline.html

# input variables that have to be provided by the triggering pipeline:
# IMAGE_REPO_NAME
# CONTAINER_NAME

phases:
  # install:
  #   runtime-versions:
  #     docker: 20
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - AWS_REGION=$AWS_DEFAULT_REGION
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - BRANCH_NAME=${BranchName}
      - echo "BRANCH_NAME is $BRANCH_NAME"
      - IMAGE_TAG=$BRANCH_NAME
      - echo "IMAGE_TAG is $IMAGE_TAG"
      - echo Pull started on `date`
      - docker pull $REPOSITORY_URI:$IMAGE_TAG || true
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --cache-from $REPOSITORY_URI:$IMAGE_TAG -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG