services:
  web:
    build: .
    ports:
      - "8000:80"
    environment:
      - DJANGO_SECRET_KEY=your-secret-key-for-testing
      - DB_NAME=newsloom
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_SSLMODE=disable
      - DJANGO_DB_SSLMODE=disable
      - ALLOWED_HOSTS=*
      - CSRF_TRUSTED_ORIGINS=http://localhost:8000,http://127.0.0.1:8000
      - CSRF_COOKIE_SECURE=0
      - CSRF_USE_SESSIONS=0
      # AWS Credentials
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    volumes:
      - ./newsloom:/app/newsloom
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./.env:/app/.env  # Mount .env file into container
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "80"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=newsloom
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGSSLMODE=disable
    ports:
      - "5432:5432"
    command: -c ssl=off

volumes:
  postgres_data:
  static_volume:
  media_volume:
