# Generated by Django 5.1.3 on 2024-11-26 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stream_type', models.CharField(choices=[('sitemap_news', 'Sitemap News Parser'), ('sitemap_blog', 'Sitemap Blog Parser'), ('rss_feed', 'RSS Feed Parser'), ('web_article', 'Web Article Scraper'), ('telegram_channel', 'Telegram Channel Monitor')], max_length=50)),
                ('frequency', models.CharField(choices=[('5min', 'Every 5 minutes'), ('15min', 'Every 15 minutes'), ('30min', 'Every 30 minutes'), ('1hour', 'Every hour'), ('6hours', 'Every 6 hours'), ('12hours', 'Every 12 hours'), ('daily', 'Daily')], max_length=20)),
                ('configuration', models.JSONField(help_text='Stream-specific configuration parameters in JSON format')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('failed', 'Failed')], default='active', max_length=20)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='sources.source')),
            ],
            options={
                'verbose_name': 'Stream',
                'verbose_name_plural': 'Streams',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stream_type'], name='streams_str_stream__b81467_idx'), models.Index(fields=['status'], name='streams_str_status_db4df2_idx'), models.Index(fields=['next_run'], name='streams_str_next_ru_10bbbc_idx')],
            },
        ),
    ]
