# Generated by Django 5.1.3 on 2024-11-27 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanager', '0001_initial'),
        ('sources', '0001_initial'),
        ('streams', '0002_alter_stream_stream_type_luigitasklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='mediamanager.media'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='sources.source'),
        ),
    ]
