# Generated by Django 5.1.3 on 2024-11-27 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanager', '0001_initial'),
        ('sources', '0001_initial'),
        ('streams', '0003_stream_media_alter_stream_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_type',
            field=models.CharField(choices=[('sitemap_news', 'Sitemap News Parser'), ('sitemap_blog', 'Sitemap Blog Parser'), ('playwright_link_extractor', 'Playwright Link Extractor'), ('rss_feed', 'RSS Feed Parser'), ('web_article', 'Web Article Scraper'), ('telegram_channel', 'Telegram Channel Monitor'), ('telegram_publisher', 'Telegram Publisher')], max_length=50),
        ),
        migrations.CreateModel(
            name='TelegramPublishLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediamanager.media')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.news')),
            ],
            options={
                'indexes': [models.Index(fields=['media', 'published_at'], name='streams_tel_media_i_0c542f_idx')],
                'unique_together': {('news', 'media')},
            },
        ),
    ]
