# Generated by Django 5.1.3 on 2024-11-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0006_alter_stream_configuration_alter_stream_stream_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='luigitasklog',
            name='output_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
