# Generated by Django 5.1.3 on 2024-12-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0010_alter_stream_stream_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('failed', 'Failed'), ('processing', 'Processing')], default='active', max_length=20),
        ),
    ]
