# Generated by Django 5.1.3 on 2024-12-16 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediamanager', '0002_examples'),
        ('sources', '0002_doc'),
        ('streams', '0011_alter_stream_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_type',
            field=models.CharField(choices=[('sitemap_news', 'Sitemap News Parser'), ('sitemap_blog', 'Sitemap Blog Parser'), ('playwright_link_extractor', 'Playwright Link Extractor'), ('rss_feed', 'RSS Feed Parser'), ('web_article', 'Web Article Scraper'), ('telegram_channel', 'Telegram Channel Monitor'), ('telegram_publish', 'Telegram Links Publisher'), ('telegram_test', 'Telegram Test Publisher'), ('article_searcher', 'Article Content Searcher'), ('bing_search', 'Bing Search'), ('telegram_bulk_parser', 'Telegram Bulk Parser'), ('news_stream', 'News Stream Processor'), ('doc_publisher', 'Doc Publisher')], max_length=50),
        ),
        migrations.CreateModel(
            name='TelegramDocPublishLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sources.doc')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediamanager.media')),
            ],
            options={
                'indexes': [models.Index(fields=['media', 'published_at'], name='streams_tel_media_i_3a2986_idx')],
                'unique_together': {('doc', 'media')},
            },
        ),
    ]
