# Generated by Django 5.1.3 on 2025-01-03 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0013_alter_stream_stream_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
