# Generated by Django 5.1.3 on 2025-01-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('edit', 'Edit'), ('publish', 'Publish'), ('failed', 'Failed')], default='new', max_length=50),
        ),
    ]
