# Generated by Django 5.1.3 on 2025-01-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_alter_doc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='google_doc_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
