# Generated by Django 5.1.5 on 2025-02-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_doc_google_doc_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
