# Generated by Django 5.1.5 on 2025-01-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_create_chats_for_existing_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='slack_channel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='slack_thread_ts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='slack_ts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
