# Generated by Django 5.1.5 on 2025-01-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_slack_channel_id_chat_slack_thread_ts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='telegram_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='telegram_message_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
