# Generated by Django 5.1.5 on 2025-01-30 00:48

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat_telegram_chat_id_chat_telegram_message_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField()),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('tool_call', 'Tool Call'), ('tool_result', 'Tool Result')], max_length=20)),
                ('content', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('tool_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tool_id', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='chat.chatmessage')),
            ],
            options={
                'ordering': ['chat_message', 'sequence_number'],
                'unique_together': {('chat_message', 'sequence_number')},
            },
        ),
    ]
